spring:
   application:
      name: fortuneteller-gateway
   cloud:
      config:
         retry:
            initialInterval: 100
            multiplier: 1.1
            maxInterval: 100
            maxAttempts: 10
server:
   port: 8080
eureka:
   instance:
      instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
      statusPageUrlPath: /actuator/info
      healthCheckUrlPath: /actuator/health
      preferIpAddress: true
   client:
      healthcheck:
         enabled: true
      serviceUrl:
         defaultZone: ${EUREKA_URL:http://localhost:8761}/eureka
security:
   oauth2:
      client:
         access-token-uri: ${OAUTH_URL:http://localhost:5000}/oauth/token
         client-id: client
         client-secret: client
         user-authorization-uri: ${OAUTH_URL:http://localhost:5000}/oauth/authorize
      resource:
         id: fortuneteller-gateway
         prefer-token-info: false
         user-info-uri: ${OAUTH_URL:http://localhost:5000}/oauth/user
zuul:
   ignoredServices: '*'
   prefix: /api
   routes:
      oauth:
         path: /oauth/**
         service-id: fortuneteller-oauth
         strip-prefix: false
      predictor:
         path: /predictor/**
         service-id: fortuneteller-predictor
         strip-prefix: false
   sensitive-headers: Cookie,Set-Cookie
   ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
management:
   metrics:
      export:
         prometheus:
            enabled: true
   endpoints:
      web:
         exposure:
            include: health,info,metrics #,routes,filters,logfile
info:
   app:
      name: '@project.artifactId@'
      description: '@project.description@'
   build:
      groupId: '@project.groupId@'
      artifact: '@project.artifactId@'
      name: '@project.name@'
      version: '@project.version@'
      encoding: '@project.build.sourceEncoding@'
   env:
      java:
         vendor: ${java.specification.vendor}
         vm-name: ${java.vm.name}
         runtime-version: ${java.runtime.version}