version: '3.3'
services:

  fortuneteller-eureka:
    build:
      context: ./fortuneteller-eureka
    container_name: fortuneteller-eureka
    ports:
      - 8761:8761
    networks:
      - fortuneteller-network

  fortuneteller-oauth:
    build:
      context: ./fortuneteller-oauth
    container_name: fortuneteller-oauth
    ports:
      - 5000:5000
    depends_on: 
      - fortuneteller-eureka
    links:
      - fortuneteller-eureka
    environment:
      - EUREKA_URL=http://fortuneteller-eureka:8761
    networks:
      - fortuneteller-network

  fortuneteller-predictor:
    build:
      context: ./fortuneteller-predictor
    container_name: fortuneteller-predictor
    ports:
      - 5001:5001
    depends_on:
      - fortuneteller-eureka
    environment:
      - EUREKA_URL=http://fortuneteller-eureka:8761
      - GATEWAY_URL=http://fortuneteller-gateway:8080
    networks:
      - fortuneteller-network

  fortuneteller-gateway:
    build:
      context: ./fortuneteller-gateway
    container_name: fortuneteller-gateway
    ports:
      - 8080:8080
    depends_on:
      - fortuneteller-eureka
      - fortuneteller-oauth
      - fortuneteller-predictor
    environment:
      - EUREKA_URL=http://fortuneteller-eureka:8761
      - OAUTH_HOST=http://fortuneteller-oauth:5000
    networks:
      - fortuneteller-network

networks:
  fortuneteller-network: