spring:
   application:
      name: fortuneteller-oauth
   cloud:
      config:
         retry:
            initialInterval: 100
            multiplier: 1.1
            maxInterval: 100
            maxAttempts: 10
server:
   port: 5000
eureka:
   instance:
      instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
      statusPageUrlPath: /actuator/info
      healthCheckUrlPath: /actuator/health
      preferIpAddress: true
   client:
      healthcheck:
         enabled: true
      serviceUrl:
         defaultZone: ${EUREKA_URL:http://localhost:8761}/eureka
security:
   oauth2:
      resource:
         jwt:
            key-alias: fortuneteller
            key-password: fortuneteller
            key-store: classpath:fortuneteller.keystore
            key-store-password: '!@#qwe45'
management:
   metrics:
      export:
         prometheus:
            enabled: true
   endpoints:
      web:
         exposure:
            include: health,info,metrics #,routes,filters,logfile
info:
   app:
      name: '@project.artifactId@'
      description: '@project.description@'
   build:
      groupId: '@project.groupId@'
      artifact: '@project.artifactId@'
      name: '@project.name@'
      version: '@project.version@'
      encoding: '@project.build.sourceEncoding@'
   env:
      java:
         vendor: ${java.specification.vendor}
         vm-name: ${java.vm.name}
         runtime-version: ${java.runtime.version}